version: '3.8'

services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: kisskh-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Italy,Germany,Netherlands,Switzerland,Sweden,Poland,France,Spain,Austria,Belgium,Czech Republic,Denmark,Finland,Norway
      - TZ=Europe/Rome
    ports:
      - "3000:3000"
      - "8191:8191"
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: kisskh-flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=hcaptcha-solver
      - HEADLESS=true
      - BROWSER_TIMEOUT=120000
      - TEST_URL=https://www.google.com
      - TZ=Europe/Rome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: "service:vpn"
    depends_on:
      - vpn

  kisskh-addon:
    image: kisskh-addon:latest
    container_name: kisskh-addon
    volumes:
      - ./cache:/app/cache
    environment:
      - FLARESOLVERR_URL=http://localhost:8191
      - FLARESOLVERR_ENABLED=true
      - PORT=3000
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
      - PUPPETEER_EXECUTABLE_PATH=
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu --hide-scrollbars --mute-audio
      - NODE_ENV=production
      - TZ=Europe/Rome
    depends_on:
      - vpn
      - flaresolverr
    restart: unless-stopped
    network_mode: "service:vpn"
