version: '3'
services:
  vpn:
    image: qmcgaw/gluetun
    container_name: kisskh-vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Italy
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped

  addon:
    build: .
    container_name: kisskh-addon
    network_mode: "service:vpn"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - vpn
    restart: unless-stopped

