services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: kisskh-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Italy,France,Spain,Germany,Netherlands,Switzerland
      - OPENVPN_PROTOCOL=udp
      - OPENVPN_VERBOSITY=1
      - OPENVPN_ROOT=no
      - HEALTH_CHECK_URL=https://www.google.com
      - TZ=Europe/Rome
      - FIREWALL_VPN_INPUT_PORTS=3000,8191
    ports:
      - "3000:3000"
      - "8191:8191"
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - npm_proxy

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: kisskh-flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=hcaptcha-solver
      - BROWSER_TIMEOUT=120000
      - TZ=Europe/Rome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: "service:vpn"
    depends_on:
      - vpn

  kisskh-addon:
    build: .
    container_name: kisskh-addon
    volumes:
      - ./cache:/app/cache
      - ./server-config.js:/app/server-config.js
    environment:
      - FLARESOLVERR_URL=http://localhost:8191
      - FLARESOLVERR_ENABLED=true
      - PORT=3000
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - TZ=Europe/Rome
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu --hide-scrollbars --mute-audio
      - NODE_ENV=production
    depends_on:
      - vpn
      - flaresolverr
    restart: unless-stopped
    network_mode: "service:vpn"

networks:
  npm_proxy:
    external: true
