version: '3.8'

services:

  kisskh-addon:
    build:
      context: .
      dockerfile: Dockerfile # Usiamo il Dockerfile principale e corretto
    container_name: kisskh-addon
    ports: 
      - 3000:3000
    volumes:
      - ./cache:/app/cache
    environment:
      FLARESOLVERR_ENABLED: "false" # Disabilitato per il test
      PORT: 3000
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      TZ: Europe/Rome
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      PUPPETEER_ARGS: --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu --hide-scrollbars --mute-audio
      NODE_ENV: production
    restart: unless-stopped
    
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true


