services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: kisskh-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Italy,Germany,Netherlands,Switzerland,Sweden,Poland,France,Spain,Austria,Belgium,Czech Republic,Denmark,Finland,Norway
    ports:
      - "${ADDON_PORT:-3000}:3000"
      - "${FLARESOLVERR_PORT:-8191}:8191"
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:9999"]
      interval: 30s
      timeout: 10s
      retries: 3

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=hcaptcha-solver
      - HEADLESS=true
      - BROWSER_TIMEOUT=120000
      - TEST_URL=https://www.google.com
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy

  baciasiatici-addon:
    build: .
    container_name: baciasiatici
    volumes:
      - ./cache:/app/cache
    env_file:
      - .env
    environment:
      - FLARESOLVERR_URL=http://localhost:8191
      - FLARESOLVERR_ENABLED=true
      - PORT=${ADDON_PORT:-3000}
    depends_on:
      - flaresolverr
    restart: unless-stopped
    network_mode: "service:vpn"
