version: '3.8'

services:
  # MODIFICA DI TEST: Disabilitiamo temporaneamente FlareSolverr e la VPN per isolare l'addon.

  kisskh-addon:
    build:
      context: .
      dockerfile: Dockerfile # Usiamo il Dockerfile principale e corretto
    container_name: kisskh-addon
    volumes:
      - ./cache:/app/cache
    environment:
      FLARESOLVERR_ENABLED: "false" # Disabilitato per il test
      PORT: 3000
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      TZ: Europe/Rome
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      PUPPETEER_ARGS: --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --disable-gpu --hide-scrollbars --mute-audio
      NODE_ENV: production
    restart: unless-stopped
    # network_mode: "service:vpn" # Disabilitato per il test
    networks:
      - npm_proxy

networks:
  npm_proxy:
    external: true
